Repository TaylorAbraham/Covert-Channels, pull requests merged in 2020-01, with the labels that each got.

#3 [7] Add CONTRIBUTING.md
  go_covert_lib/CONTRIBUTING.md
  go_covert_lib/README.md
Labels: documentation

#24 [23] Add names and groups to all structs
  go_covert_lib/controller/channel/ipv4tcp/ipv4_tcp_config.go
  go_covert_lib/controller/channel/tcp/tcp_config.go
  go_covert_lib/controller/config/config_util.go
  go_covert_lib/controller/processor/caesar/caesar_config.go
Labels: Backend, Ready for Review

#4 [21] Create React frontend for Covert Channel configuration
  go_covert_lib/build_watch.sh
  go_covert_lib/client/.eslintrc.json
  go_covert_lib/client/README.md
  go_covert_lib/client/client_watch.sh
  go_covert_lib/client/package-lock.json
  go_covert_lib/client/package.json
  go_covert_lib/client/public/index.html
  go_covert_lib/client/src/App.jsx
  go_covert_lib/client/src/App.test.jsx
  go_covert_lib/client/src/App.tsx
  go_covert_lib/client/src/index.jsx
  go_covert_lib/client/src/react-app-env.d.js
  go_covert_lib/client/src/serviceWorker.js
  go_covert_lib/client/src/styles.css
  go_covert_lib/client/tsconfig.json
Labels: Frontend, Ready for Review

#26 8/adding aes encryption
  go_covert_lib/controller/config/config_util.go
  go_covert_lib/controller/controller.go
  go_covert_lib/controller/controller_open.go
  go_covert_lib/controller/controller_types.go
  go_covert_lib/controller/processor/asymmetricEncryption/asymmetricEncryption.go
  go_covert_lib/controller/processor/asymmetricEncryption/asymmetricEncryption_config.go
  go_covert_lib/controller/processor/asymmetricEncryption/asymmetricEncryption_test.go
  go_covert_lib/controller/processor/symmetricEncryption/symmetricEncryption.go
  go_covert_lib/controller/processor/symmetricEncryption/symmetricEncryption_config.go
  go_covert_lib/controller/processor/symmetricEncryption/symmetricEncryption_test.go
  go_covert_lib/test.html
Labels: Backend, WIP
